# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.boot_timeout = 1500

  (1..2).each do |i|
    config.vm.define "fedora37-#{i}" do |os|
      os.vm.provider :libvirt do |libvirt|
        libvirt.cpus = 4
        libvirt.memory = "4096"
      end
      os.vm.provision "file", source: "mararc", destination: "/home/vagrant/mararc"
      os.vm.provision "file", source: "db.ao.dev", destination: "/home/vagrant/maradns/db.ao.dev"
      os.vm.provision "file", source: "resolv.conf", destination: "/home/vagrant/resolv.conf"

      ### Kerberos 5 Provisioning
      os.vm.provision "file", source: "kdc.conf", destination: "/home/vagrant/var/kerberos/krb5kdc/kdc.conf"
      os.vm.provision "file", source: "krb5.conf", destination: "/home/vagrant/etc/krb5.conf"
      os.vm.provision "file", source: "kadm5.acl", destination: "/home/vagrant/var/kerberos/krb5kdc/kadm5.acl"

      os.vm.provision "provision-script", type: "shell", path: "provision/fedora/provision.sh"
      # os.vm.provision "provision-script", type: "shell", path: "provision/fedora/krb5-provision.sh"
    end
  end
end
