services:
  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:v3.0
    # Enables the web UI
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./10.202.0.175.nip.io+2-key.pem:/certs/10.202.0.175.nip.io+2-key.pem
      - ./10.202.0.175.nip.io+2.pem:/certs/10.202.0.175.nip.io+2.pem
      - ./traefik_v3.toml:/etc/traefik/traefik.toml
      - ./traefik_dynamic.toml:/etc/traefik/traefik_dynamic.toml
      - ./traefik.logs.d/:/var/log/

  flaskapp:
    # Our current flask application
    image: flaskapp:latest
    build:
      dockerfile: ./Dockerfile.composed

    expose:
      # The Web UI port
      - "5000:5000"

  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami

    expose:
      - "80:80"

    labels:
      - "traefik.http.routers.api.rule=Host(`whoami.10.202.0.175.nip.io`)"
      - "traefik.http.routers.api.rule=Path(`/whoami`)"