# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "valengus/windows11-22h2-x64"

  config.vm.provider :libvirt do |librvirt|
    # Customize the amount of memory on the VM:
    librvirt.memory = "4096"
  end

end
